Initial version of metadata plugin
arcalot/arcaflow-plugin-metadata pull request #1
Opened 2022-10-14 23:30 UTC by jaredoconnell

## Changes introduced with this PR

These changes make the plugin successfully gather ansible facts and output them.

Currently depends on main branch of python SDK due to Any type support requirement. Will change once it's released.

---
By contributing to this repository, I agree to the [contribution guidelines](https://github.com/arcalot/.github/blob/main/CONTRIBUTING.md).

2022-10-15 02:46 UTC, portante commented on metadata_plugin.py
> +    This is the output data structure in the error  case.
If you come back to edit this file again, perhaps remove the extra space if you think of it.

2022-10-15 02:46 UTC, portante commented on metadata_plugin.py
> +
... and the extra blank line.

2022-10-15 03:00 UTC, portante requested changes
Is the `output.txt` file necessary?

2022-10-15 03:00 UTC, portante commented on metadata_plugin.py
> +    if type_of_val == float or type_of_val == int or type_of_val == str or \
Consider:

```
if type_of_val in (float, int, str, bool, type(None)):
```

2022-10-15 03:00 UTC, portante commented on metadata_plugin.py
> +            result[ convert_to_supported_type(k)] =  convert_to_supported_type(ansible_value[k])
Extra spaces in this like throw off the code a bit.  If you think of it, and come back to this file for something else, perhaps remove them?

2022-10-15 03:00 UTC, portante commented on metadata_plugin.py
> +            new_list.append( convert_to_supported_type(i))
Are we using `black` yet?

2022-10-15 03:00 UTC, portante commented on metadata_plugin.py
> +    elif type_of_val == AnsibleUnsafeText:
Consider a small change to lines 123 - 127 as:

```
else:
    value = str(ansible_value)
    if type_of_val != AnsibleUnsafeText:
        print(f"Unknown type '{type_of_val}' with value '{value}'")
    return value
```

2022-10-15 03:00 UTC, portante commented on metadata_plugin.py
> +    host_ansible_facts = vars["hostvars"][host]["ansible_facts"]
Is it worth catching `KeyError` here in order to emit a more sensible error message when Ansible fails to return data in the format expected?

2022-10-15 03:00 UTC, portante commented on metadata_plugin.py
> +    # Convert to dict
Perhaps consider, "Convert to supported types"?

2022-10-15 03:00 UTC, portante commented on metadata_plugin.py
> +    output =  convert_to_supported_type(host_ansible_facts)
If you happen to come back in here, consider fixing the extra space ... or run `black` on the file.

2022-10-15 03:00 UTC, portante commented on metadata_plugin.py
> +def  convert_to_supported_type(ansible_value):
Consider creating a function documentation string, and the extra whitespace.

2022-10-17 15:38 UTC, mfleader approved these changes

2022-10-17 18:06 UTC, jdowni000 approved these changes

2022-10-17 20:20 UTC, merged